db.createCollection("users")
db.createCollection("addresses")
db.createCollection("categories")
db.createCollection("products")
db.createCollection("product_images")
db.createCollection("orders")
db.createCollection("order_items")
db.createCollection("payments")
db.createCollection("reviews")
db.createCollection("inventory_logs")

db.users.createIndex({ id: 1 })
db.products.createIndex({ id: 1 })
db.orders.createIndex({ user_id: 1 })
db.order_items.createIndex({ order_id: 1 })
db.reviews.createIndex({ product_id: 1 })